2019.2 compat: Add com.intellij.modules.java, fix ClassCastException
- Add a dependency on com.intellij.modules.java. This is now required
for 2019.2 compatibility (see links below).
- This also fixes the NoClassDefFoundError, ClassNotFoundException for
com.intellij.psi.PsiJavaFile and
com.intellij.psi.impl.JavaPsiImplementationHelper that would occur when
EclipseFormatter is used as a bundled plugin (i.e. put directly into the
installation /plugins folder rather than installing it from the plugin
repository).

Official announcements and documentation:
https://blog.jetbrains.com/platform/2019/06/java-functionality-extracted-as-a-plugin/
http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/plugin_compatibility.html